# Generated by Django 5.0.3 on 2024-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet_name',
            field=models.CharField(default='zone', max_length=100),
        ),
    ]
