# Generated by Django 5.0.3 on 2024-04-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
